## generated by rang, do not edit by hand

current.r.version <- paste(R.Version()[c("major","minor")], collapse = ".", sep = "")

if (Sys.getenv("CACHE_PATH") != "") {
    path <- file.path(Sys.getenv("CACHE_PATH"), "rpkgs")
} else {
    path <- tempdir()
}

.install.packages <- function(tarball.path, lib, verbose, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.0") != -1) {
        if (is.na(lib)) {
            install.packages(pkg = tarball.path, repos = NULL, verbose = verbose, quiet = !verbose)
        } else {
            install.packages(pkg = tarball.path, lib = lib, repos = NULL, verbose = verbose, quiet = !verbose)
        }
    } else {
        if (is.na(lib)) {
            install.packages(pkg = tarball.path, repos = NULL)
        } else {
            install.packages(pkg = tarball.path, lib = lib, repos = NULL)
        }
    }
}

.download.package <- function(tarball.path, x, version, handle, source, uid, verbose, cran.mirror, bioc.mirror, current.r.version) {
    if (source == "github") {
        return(.download.package.from.github(tarball.path, x, version, handle, source, uid, current.r.version))
    }
    if (source == "bioc") {
        url <- paste(bioc.mirror, uid, "/src/contrib/", x, "_", version, ".tar.gz", sep = "")
    }
    if (source == "cran") {
        url <- paste(cran.mirror, "src/contrib/Archive/", x, "/", x, "_", version, ".tar.gz", sep = "")
    }

    tryCatch({
        suppressWarnings(download.file(url, destfile = tarball.path, quiet = !verbose))
    }, error = function(e) {
        if (source == "cran") {
            ## is the current latest
            url <- paste(cran.mirror, "src/contrib/", x, "_", version, ".tar.gz", sep = "")
            download.file(url, destfile = tarball.path, quiet = !verbose)
        }
    })
    invisible(tarball.path)
}

.tempfile <- function(tmpdir = tempdir(), fileext = ".tar.gz") {
    file.path(tmpdir,
    paste(paste(sample(c(LETTERS, letters), 20, replace = TRUE), collapse = ""), fileext, sep = ""))
}

.build.raw.tarball <- function(raw.tarball.path, x, version, tarball.path, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.1") != -1) {
        vignetteflag <- "--no-build-vignettes"
    } else {
        vignetteflag <- "--no-vignettes"
    }
    tmp.dir <- .tempfile(fileext = "")
    dir.create(tmp.dir)
    system(command = paste("tar", "-zxf ", raw.tarball.path, "-C", tmp.dir))
    pkg.dir <- list.files(path = tmp.dir, full.names = TRUE)[1]
    new.pkg.dir <- file.path(tmp.dir, x)
    file.rename(pkg.dir, new.pkg.dir)
    res <- system(command = paste("R", "CMD", "build", vignetteflag, new.pkg.dir))
    expected.tarball.path <- paste(x, "_", version, ".tar.gz", sep = "")
    stopifnot(file.exists(expected.tarball.path))
    file.rename(expected.tarball.path, tarball.path)
    return(tarball.path)
}

.build.dir.tarball <- function(dir.pkg.path, x, version, tarball.path, current.r.version) {
    if (utils::compareVersion(current.r.version, "3.1") != -1) {
        vignetteflag <- "--no-build-vignettes"
    } else {
        vignetteflag <- "--no-vignettes"
    }
    expected.tarball.path <- paste(x, "_", version, ".tar.gz", sep = "")
    res <- system(command = paste("R", "CMD", "build", vignetteflag, dir.pkg.path))
    stopifnot(file.exists(expected.tarball.path))
    file.rename(expected.tarball.path, tarball.path)
    return(tarball.path)
}

.install.from.source <- function(x, version, handle, source, uid, lib,
                                 path = tempdir(), verbose, cran.mirror, bioc.mirror, current.r.version) {
    tarball.path <- file.path(path, paste(x, "_", version, ".tar.gz", sep = ""))
    raw.tarball.path <- file.path(path, paste("raw_", x, "_", version, ".tar.gz", sep = ""))
    dir.pkg.path <- file.path(path, paste("dir_", x, "_", version, sep = ""))
    if (!file.exists(tarball.path) && !file.exists(raw.tarball.path) && !file.exists(dir.pkg.path)) {
        .download.package(tarball.path = tarball.path, x = x, version = version, handle = handle, source = source,
                          uid = uid, verbose = verbose, cran.mirror = cran.mirror, bioc.mirror = bioc.mirror,
                          current.r.version = current.r.version)
    }
    if (file.exists(raw.tarball.path)) {
        tarball.path <- .build.raw.tarball(raw.tarball.path, x = x, version = version, tarball.path,
                                           current.r.version = current.r.version)
        if (!file.exists(tarball.path)) {
            stop("building failed.")
        }
    }
    if (file.exists(dir.pkg.path)) {
        tarball.path <- .build.dir.tarball(dir.pkg.path, x = x, version = version, tarball.path,
                                           current.r.version = current.r.version)
        if (!file.exists(tarball.path)) {
            stop("building failed.")
        }
    }
    .install.packages(tarball.path, lib, verbose, current.r.version)
    ## check and error
    if (!is.na(lib)) {
        installed.packages <- installed.packages(lib.loc = lib)
    } else {
        installed.packages <- installed.packages()
    }
    if (!x %in% dimnames(installed.packages)[[1]]) {
        stop("Fail to install ", x, "\n")
    }
    invisible()
}

# installing github packages
.download.github.safe <- function(handle, sha, file) {
    tryCatch(
        download.file(paste("http://api.github.com/repos/", handle, "/tarball/", sha, sep = ""), destfile = file),
        error = function(e) {
            stop(paste("couldn't download ", handle, " from github", sep = ""), call. = FALSE)
        }
    )
}

.download.package.from.github <- function(tarball.path, x, version, handle, source, uid, current.r.version) {
    sha <- uid
    short.sha <- substr(sha, 1, 7)
    raw.tarball.path <- .tempfile(fileext = ".tar.gz")
    tmp.dir <- tempdir()
    tryCatch(
        download.file(paste("https://api.github.com/repos/", handle, "/tarball/", sha, sep = ""), destfile = raw.tarball.path),
        error = function(e) {
            .download.github.safe(handle, sha, raw.tarball.path)
        }
    )
    .build.raw.tarball(raw.tarball.path = raw.tarball.path, x = x, version = version, tarball.path = tarball.path, current.r.version = current.r.version)
    return(tarball.path)
}
installation.order <- structure(list(x = c("lattice", "sp", "rgdal"), version = c("0.20-35", 
"1.2-5", "1.2-16"), source = c("cran", "cran", "cran"), handle = c("lattice", 
"sp", "rgdal"), uid = c(NA_character_, NA_character_, NA_character_
)), class = "data.frame", row.names = c(NA, -3L))

verbose <- TRUE
lib <- NA
cran.mirror <- "https://cran.r-project.org/"
bioc.mirror <- "https://bioconductor.org/packages/3.6/"

if (nrow(installation.order) >= 1) {
    for (i in seq(from = 1, to = nrow(installation.order), by = 1)) {
        x <- installation.order$x[i]
        source <- installation.order$source[i]
        version <- installation.order$version[i]
        handle <- installation.order$handle[i]
        uid <- installation.order$uid[i]
        .install.from.source(x = x, version = version, handle = handle, source = source, uid = uid,
                             lib = lib, path = path, verbose = verbose,
                             cran.mirror = cran.mirror, bioc.mirror = bioc.mirror,
                             current.r.version = current.r.version)
    }
}
## ## To reconstruct this file, please install version 0.3.0 of `rang` and run:
## rang <- 
## structure(list(call = resolve(pkgs = c("sp", "rgdal"), snapshot_date = "2017-11-30"), 
##     ranglets = list(`cran::sp` = structure(list(pkgref = "cran::sp", 
##         no_enhances = TRUE, no_suggests = TRUE, snapshot_date = structure(1.512e+09, class = c("POSIXct", 
##         "POSIXt"), tzone = "UTC"), original = structure(list(
##             snapshot_date = structure(c(1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09), class = c("POSIXct", "POSIXt"
##             ), tzone = "UTC"), x = c("sp", "sp", "sp", "sp", 
##             "sp", "sp", "sp", "sp", "sp", "sp", "sp", "sp", "sp", 
##             "sp"), x_version = c("1.2-5", "1.2-5", "1.2-5", "1.2-5", 
##             "1.2-5", "1.2-5", "1.2-5", "1.2-5", "1.2-5", "1.2-5", 
##             "1.2-5", "1.2-5", "1.2-5", "1.2-5"), x_pubdate = structure(c(1498727336, 
##             1498727336, 1498727336, 1498727336, 1498727336, 1498727336, 
##             1498727336, 1498727336, 1498727336, 1498727336, 1498727336, 
##             1498727336, 1498727336, 1498727336), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x_pkgref = c("cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp", "cran::sp", "cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp", "cran::sp", "cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp"), y = c("R", "methods", 
##             "utils", "stats", "graphics", "grDevices", "lattice", 
##             "grid", "RColorBrewer", "rgdal", "rgeos", "gstat", 
##             "maptools", "deldir"), type = c("Depends", "Depends", 
##             "Imports", "Imports", "Imports", "Imports", "Imports", 
##             "Imports", "Suggests", "Suggests", "Suggests", "Suggests", 
##             "Suggests", "Suggests"), y_raw_version = c(">= 3.0.0", 
##             "*", "*", "*", "*", "*", "*", "*", "*", ">= 0.8-7", 
##             ">= 0.3-13", "*", "*", "*"), y_pkgref = c("cran::R", 
##             "cran::methods", "cran::utils", "cran::stats", "cran::graphics", 
##             "cran::grDevices", "cran::lattice", "cran::grid", 
##             "cran::RColorBrewer", "cran::rgdal", "cran::rgeos", 
##             "cran::gstat", "cran::maptools", "cran::deldir")), class = "data.frame", row.names = c(NA, 
##         -14L)), deps = list(`cran::lattice` = structure(list(
##             snapshot_date = structure(c(1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x = c("lattice", "lattice", 
##             "lattice", "lattice", "lattice", "lattice", "lattice", 
##             "lattice", "lattice", "lattice"), x_version = c("0.20-35", 
##             "0.20-35", "0.20-35", "0.20-35", "0.20-35", "0.20-35", 
##             "0.20-35", "0.20-35", "0.20-35", "0.20-35"), x_pubdate = structure(c(1490465331, 
##             1490465331, 1490465331, 1490465331, 1490465331, 1490465331, 
##             1490465331, 1490465331, 1490465331, 1490465331), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x_pkgref = c("cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice"
##             ), y = c("R", "KernSmooth", "MASS", "latticeExtra", 
##             "grid", "grDevices", "graphics", "stats", "utils", 
##             "chron"), type = c("Depends", "Suggests", "Suggests", 
##             "Suggests", "Imports", "Imports", "Imports", "Imports", 
##             "Imports", "Enhances"), y_raw_version = c(">= 3.0.0", 
##             "*", "*", "*", "*", "*", "*", "*", "*", "*"), y_pkgref = c("cran::R", 
##             "cran::KernSmooth", "cran::MASS", "cran::latticeExtra", 
##             "cran::grid", "cran::grDevices", "cran::graphics", 
##             "cran::stats", "cran::utils", "cran::chron")), class = "data.frame", row.names = c(NA, 
##         -10L))), unresolved_deps = character(0)), class = "ranglet"), 
##         `cran::rgdal` = structure(list(pkgref = "cran::rgdal", 
##             no_enhances = TRUE, no_suggests = TRUE, snapshot_date = structure(1.512e+09, class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), original = structure(list(
##                 snapshot_date = structure(c(1.512e+09, 1.512e+09, 
##                 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##                 1.512e+09), class = c("POSIXct", "POSIXt"), tzone = "UTC"), 
##                 x = c("rgdal", "rgdal", "rgdal", "rgdal", "rgdal", 
##                 "rgdal", "rgdal", "rgdal"), x_version = c("1.2-16", 
##                 "1.2-16", "1.2-16", "1.2-16", "1.2-16", "1.2-16", 
##                 "1.2-16", "1.2-16"), x_pubdate = structure(c(1511288464, 
##                 1511288464, 1511288464, 1511288464, 1511288464, 
##                 1511288464, 1511288464, 1511288464), class = c("POSIXct", 
##                 "POSIXt"), tzone = "UTC"), x_pkgref = c("cran::rgdal", 
##                 "cran::rgdal", "cran::rgdal", "cran::rgdal", 
##                 "cran::rgdal", "cran::rgdal", "cran::rgdal", 
##                 "cran::rgdal"), y = c("R", "methods", "sp", "grDevices", 
##                 "graphics", "stats", "utils", "sp"), type = c("Depends", 
##                 "Depends", "Depends", "Imports", "Imports", "Imports", 
##                 "Imports", "LinkingTo"), y_raw_version = c(">= 3.3.0", 
##                 "*", ">= 1.1-0", "*", "*", "*", "*", "*"), y_pkgref = c("cran::R", 
##                 "cran::methods", "cran::sp", "cran::grDevices", 
##                 "cran::graphics", "cran::stats", "cran::utils", 
##                 "cran::sp")), class = "data.frame", row.names = c(NA, 
##             -8L)), deps = list(`cran::sp` = structure(list(snapshot_date = structure(c(1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x = c("sp", "sp", "sp", 
##             "sp", "sp", "sp", "sp", "sp", "sp", "sp", "sp", "sp", 
##             "sp", "sp"), x_version = c("1.2-5", "1.2-5", "1.2-5", 
##             "1.2-5", "1.2-5", "1.2-5", "1.2-5", "1.2-5", "1.2-5", 
##             "1.2-5", "1.2-5", "1.2-5", "1.2-5", "1.2-5"), x_pubdate = structure(c(1498727336, 
##             1498727336, 1498727336, 1498727336, 1498727336, 1498727336, 
##             1498727336, 1498727336, 1498727336, 1498727336, 1498727336, 
##             1498727336, 1498727336, 1498727336), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x_pkgref = c("cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp", "cran::sp", "cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp", "cran::sp", "cran::sp", 
##             "cran::sp", "cran::sp", "cran::sp"), y = c("R", "methods", 
##             "utils", "stats", "graphics", "grDevices", "lattice", 
##             "grid", "RColorBrewer", "rgdal", "rgeos", "gstat", 
##             "maptools", "deldir"), type = c("Depends", "Depends", 
##             "Imports", "Imports", "Imports", "Imports", "Imports", 
##             "Imports", "Suggests", "Suggests", "Suggests", "Suggests", 
##             "Suggests", "Suggests"), y_raw_version = c(">= 3.0.0", 
##             "*", "*", "*", "*", "*", "*", "*", "*", ">= 0.8-7", 
##             ">= 0.3-13", "*", "*", "*"), y_pkgref = c("cran::R", 
##             "cran::methods", "cran::utils", "cran::stats", "cran::graphics", 
##             "cran::grDevices", "cran::lattice", "cran::grid", 
##             "cran::RColorBrewer", "cran::rgdal", "cran::rgeos", 
##             "cran::gstat", "cran::maptools", "cran::deldir")), class = "data.frame", row.names = c(NA, 
##             -14L)), `cran::lattice` = structure(list(snapshot_date = structure(c(1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09, 
##             1.512e+09, 1.512e+09, 1.512e+09, 1.512e+09), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x = c("lattice", "lattice", 
##             "lattice", "lattice", "lattice", "lattice", "lattice", 
##             "lattice", "lattice", "lattice"), x_version = c("0.20-35", 
##             "0.20-35", "0.20-35", "0.20-35", "0.20-35", "0.20-35", 
##             "0.20-35", "0.20-35", "0.20-35", "0.20-35"), x_pubdate = structure(c(1490465331, 
##             1490465331, 1490465331, 1490465331, 1490465331, 1490465331, 
##             1490465331, 1490465331, 1490465331, 1490465331), class = c("POSIXct", 
##             "POSIXt"), tzone = "UTC"), x_pkgref = c("cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice", 
##             "cran::lattice", "cran::lattice", "cran::lattice"
##             ), y = c("R", "KernSmooth", "MASS", "latticeExtra", 
##             "grid", "grDevices", "graphics", "stats", "utils", 
##             "chron"), type = c("Depends", "Suggests", "Suggests", 
##             "Suggests", "Imports", "Imports", "Imports", "Imports", 
##             "Imports", "Enhances"), y_raw_version = c(">= 3.0.0", 
##             "*", "*", "*", "*", "*", "*", "*", "*", "*"), y_pkgref = c("cran::R", 
##             "cran::KernSmooth", "cran::MASS", "cran::latticeExtra", 
##             "cran::grid", "cran::grDevices", "cran::graphics", 
##             "cran::stats", "cran::utils", "cran::chron")), class = "data.frame", row.names = c(NA, 
##             -10L))), unresolved_deps = character(0)), class = "ranglet")), 
##     snapshot_date = structure(1.512e+09, class = c("POSIXct", 
##     "POSIXt"), tzone = "UTC"), no_enhances = TRUE, no_suggests = TRUE, 
##     unresolved_pkgrefs = character(0), sysreqs = c("apt-get install -y libgdal-dev", 
##     "apt-get install -y gdal-bin", "apt-get install -y libproj-dev"
##     ), r_version = "3.4.2", bioc_version = "3.6", os = "ubuntu-20.04"), class = "rang")
## rang::export_rang(rang = rang, path = "./d_legacy-rstudio-spatial/rang.R", verbose = TRUE, lib = NA, cran_mirror = "https://cran.r-project.org/", check_cran_mirror = TRUE, bioc_mirror = "https://bioconductor.org/packages/3.6/")
